/**
 * @fileoverview Seed Inventory Items for SPPG
 * @version Prisma 6.17.1
 * @description Inventory Items = Stok bahan di gudang SPPG (master data)
 *              MenuIngredient = Bahan yang sudah ditambahkan ke menu tertentu
 */

import { PrismaClient, InventoryCategory } from '@prisma/client'

const prisma = new PrismaClient()

export async function seedInventory() {
  console.log('  → Creating inventory items...')

  // Get first active SPPG
  const sppg = await prisma.sPPG.findFirst({
    where: { status: 'ACTIVE' }
  })

  if (!sppg) {
    console.log('  ⚠️  No active SPPG found. Skipping inventory seed.')
    return
  }

  const inventoryItems: Array<{
    itemName: string
    itemCode: string
    category: InventoryCategory
    unit: string
    currentStock: number
    minStock: number
    maxStock: number
    costPerUnit: number
    storageLocation: string
    storageCondition?: string
    isActive: boolean
    sppgId: string
    // Nutrition data (per 100g/100ml) - Based on TKPI (Tabel Komposisi Pangan Indonesia)
    calories?: number
    protein?: number
    carbohydrates?: number
    fat?: number
    fiber?: number
    // Vitamins (per 100g)
    vitaminA?: number       // mcg RAE
    vitaminB1?: number      // mg (Thiamin)
    vitaminB2?: number      // mg (Riboflavin)
    vitaminB3?: number      // mg (Niacin)
    vitaminB6?: number      // mg
    vitaminB12?: number     // mcg
    vitaminC?: number       // mg
    vitaminD?: number       // mcg
    vitaminE?: number       // mg
    vitaminK?: number       // mcg
    folate?: number         // mcg
    // Minerals (per 100g)
    calcium?: number        // mg
    iron?: number           // mg
    magnesium?: number      // mg
    phosphorus?: number     // mg
    potassium?: number      // mg
    sodium?: number         // mg
    zinc?: number           // mg
    selenium?: number       // mcg
    iodine?: number         // mcg
  }> = [
    // KARBOHIDRAT
    {
      itemName: 'Beras Merah',
      itemCode: 'BRM-001',
      category: 'KARBOHIDRAT',
      unit: 'kg',
      currentStock: 150,
      minStock: 50,
      maxStock: 500,
      costPerUnit: 15000,
      storageLocation: 'Gudang Kering',
      storageCondition: 'DRY',
      isActive: true,
      sppgId: sppg.id,
      // Nutrition per 100g (TKPI Data)
      calories: 110,
      protein: 2.5,
      carbohydrates: 23,
      fat: 0.9,
      fiber: 1.8,
      // Vitamins
      vitaminB1: 0.15,
      vitaminB2: 0.05,
      vitaminB3: 1.9,
      vitaminB6: 0.2,
      folate: 8,
      // Minerals
      calcium: 10,
      iron: 0.8,
      magnesium: 43,
      phosphorus: 108,
      potassium: 86,
      sodium: 1,
      zinc: 1.1
    },
    {
      itemName: 'Beras Putih',
      itemCode: 'BRP-001',
      category: 'KARBOHIDRAT',
      unit: 'kg',
      currentStock: 200,
      minStock: 80,
      maxStock: 600,
      costPerUnit: 12000,
      storageLocation: 'Gudang Kering',
      storageCondition: 'DRY',
      isActive: true,
      sppgId: sppg.id,
      calories: 130,
      protein: 2.4,
      carbohydrates: 28,
      fat: 0.3,
      fiber: 0.2,
      // Vitamins
      vitaminB1: 0.07,
      vitaminB2: 0.03,
      vitaminB3: 1.6,
      vitaminB6: 0.15,
      folate: 3,
      // Minerals
      calcium: 6,
      iron: 0.5,
      magnesium: 12,
      phosphorus: 43,
      potassium: 35,
      sodium: 1,
      zinc: 0.6
    },
    {
      itemName: 'Tepung Terigu',
      itemCode: 'TPT-001',
      category: 'KARBOHIDRAT',
      unit: 'kg',
      currentStock: 75,
      minStock: 30,
      maxStock: 200,
      costPerUnit: 10000,
      storageLocation: 'Gudang Kering',
      storageCondition: 'DRY',
      isActive: true,
      sppgId: sppg.id,
      calories: 364,
      protein: 10,
      carbohydrates: 76,
      fat: 1,
      fiber: 2.7,
      // Vitamins
      vitaminB1: 0.4,
      vitaminB2: 0.2,
      vitaminB3: 4,
      vitaminB6: 0.2,
      folate: 26,
      // Minerals
      calcium: 15,
      iron: 1.2,
      magnesium: 22,
      phosphorus: 108,
      potassium: 107,
      sodium: 2,
      zinc: 0.7
    },
    {
      itemName: 'Mie Telur',
      itemCode: 'MIE-001',
      category: 'KARBOHIDRAT',
      unit: 'kg',
      currentStock: 30,
      minStock: 15,
      maxStock: 100,
      costPerUnit: 18000,
      storageLocation: 'Gudang Kering',
      storageCondition: 'DRY',
      isActive: true,
      sppgId: sppg.id,
      calories: 380,
      protein: 13,
      carbohydrates: 73,
      fat: 3.5,
      fiber: 2,
      // Vitamins
      vitaminA: 50,
      vitaminB1: 0.3,
      vitaminB2: 0.2,
      vitaminB3: 3,
      vitaminB6: 0.15,
      folate: 20,
      // Minerals
      calcium: 20,
      iron: 1.8,
      magnesium: 25,
      phosphorus: 120,
      potassium: 95,
      sodium: 400,
      zinc: 1
    },
    {
      itemName: 'Tepung Beras',
      itemCode: 'TPG-001',
      category: 'KARBOHIDRAT',
      unit: 'kg',
      currentStock: 40,
      minStock: 15,
      maxStock: 120,
      costPerUnit: 10000,
      storageLocation: 'Gudang Kering',
      storageCondition: 'DRY',
      isActive: true,
      sppgId: sppg.id,
      calories: 366,
      protein: 6,
      carbohydrates: 80,
      fat: 0.7,
      fiber: 1.3,
      // Vitamins
      vitaminB1: 0.06,
      vitaminB2: 0.02,
      vitaminB3: 1.3,
      vitaminB6: 0.1,
      folate: 4,
      // Minerals
      calcium: 5,
      iron: 0.4,
      magnesium: 9,
      phosphorus: 36,
      potassium: 30,
      sodium: 1,
      zinc: 0.5
    },
    {
      itemName: 'Roti Gandum',
      itemCode: 'ROT-001',
      category: 'KARBOHIDRAT',
      unit: 'kg',
      currentStock: 20,
      minStock: 10,
      maxStock: 80,
      costPerUnit: 30000,
      storageLocation: 'Gudang Kering',
      storageCondition: 'ROOM_TEMP',
      isActive: true,
      sppgId: sppg.id,
      calories: 247,
      protein: 8.8,
      carbohydrates: 41,
      fat: 3.4,
      fiber: 6.7,
      // Vitamins
      vitaminB1: 0.2,
      vitaminB2: 0.1,
      vitaminB3: 3.5,
      vitaminB6: 0.2,
      vitaminE: 0.3,
      folate: 30,
      // Minerals
      calcium: 100,
      iron: 2.5,
      magnesium: 70,
      phosphorus: 180,
      potassium: 220,
      sodium: 450,
      zinc: 1.5
    },

    // PROTEIN HEWANI
    {
      itemName: 'Ayam Fillet',
      itemCode: 'AYM-001',
      category: 'PROTEIN',
      unit: 'kg',
      currentStock: 40,
      minStock: 20,
      maxStock: 100,
      costPerUnit: 45000,
      storageLocation: 'Freezer',
      storageCondition: 'FROZEN',
      isActive: true,
      sppgId: sppg.id,
      calories: 165,
      protein: 31,
      carbohydrates: 0,
      fat: 3.6,
      fiber: 0,
      // Vitamins
      vitaminA: 21,
      vitaminB1: 0.08,
      vitaminB2: 0.12,
      vitaminB3: 10.9,
      vitaminB6: 0.6,
      vitaminB12: 0.3,
      folate: 4,
      // Minerals
      calcium: 11,
      iron: 0.9,
      magnesium: 29,
      phosphorus: 220,
      potassium: 340,
      sodium: 70,
      zinc: 1.3,
      selenium: 27
    },
    {
      itemName: 'Daging Sapi',
      itemCode: 'DSP-001',
      category: 'PROTEIN',
      unit: 'kg',
      currentStock: 25,
      minStock: 10,
      maxStock: 60,
      costPerUnit: 120000,
      storageLocation: 'Freezer',
      storageCondition: 'FROZEN',
      isActive: true,
      sppgId: sppg.id,
      calories: 250,
      protein: 26,
      carbohydrates: 0,
      fat: 17,
      fiber: 0
    },
    {
      itemName: 'Telur Ayam',
      itemCode: 'TLR-001',
      category: 'PROTEIN',
      unit: 'kg',
      currentStock: 50,
      minStock: 30,
      maxStock: 150,
      costPerUnit: 28000,
      storageLocation: 'Chiller',
      storageCondition: 'COOL',
      isActive: true,
      sppgId: sppg.id,
      calories: 155,
      protein: 12.6,
      carbohydrates: 0.7,
      fat: 10.6,
      fiber: 0,
      // Vitamins (TKPI Data)
      vitaminA: 160,
      vitaminB1: 0.04,
      vitaminB2: 0.44,
      vitaminB3: 0.07,
      vitaminB6: 0.17,
      vitaminB12: 0.89,
      vitaminD: 2,
      vitaminE: 1,
      folate: 47,
      // Minerals
      calcium: 50,
      iron: 1.8,
      magnesium: 12,
      phosphorus: 198,
      potassium: 138,
      sodium: 124,
      zinc: 1.3,
      selenium: 30
    },
    {
      itemName: 'Tempe',
      itemCode: 'TMP-001',
      category: 'PROTEIN',
      unit: 'kg',
      currentStock: 25,
      minStock: 15,
      maxStock: 60,
      costPerUnit: 12000,
      storageLocation: 'Chiller',
      storageCondition: 'COOL',
      isActive: true,
      sppgId: sppg.id,
      calories: 201,
      protein: 20.8,
      carbohydrates: 13.5,
      fat: 8.8,
      fiber: 1.4,
      // Vitamins (TKPI Data)
      vitaminB1: 0.15,
      vitaminB2: 0.65,
      vitaminB3: 4,
      vitaminB6: 0.3,
      vitaminB12: 0.08,
      folate: 24,
      // Minerals
      calcium: 155,
      iron: 4,
      magnesium: 81,
      phosphorus: 326,
      potassium: 234,
      sodium: 9,
      zinc: 1.7
    },
    {
      itemName: 'Tahu',
      itemCode: 'TAH-001',
      category: 'PROTEIN',
      unit: 'kg',
      currentStock: 18,
      minStock: 8,
      maxStock: 40,
      costPerUnit: 10000,
      storageLocation: 'Chiller',
      storageCondition: 'COOL',
      isActive: true,
      sppgId: sppg.id,
      calories: 76,
      protein: 8,
      carbohydrates: 1.9,
      fat: 4.8,
      fiber: 0.3,
      // Vitamins (TKPI Data)
      vitaminB1: 0.06,
      vitaminB2: 0.05,
      vitaminB3: 0.2,
      vitaminB6: 0.05,
      folate: 15,
      // Minerals
      calcium: 350,      // TINGGI kalsium!
      iron: 5.4,         // TINGGI zat besi!
      magnesium: 37,
      phosphorus: 183,
      potassium: 121,
      sodium: 7,
      zinc: 0.8
    },
    {
      itemName: 'Kedelai Kuning',
      itemCode: 'KDL-001',
      category: 'PROTEIN',
      unit: 'kg',
      currentStock: 25,
      minStock: 10,
      maxStock: 80,
      costPerUnit: 15000,
      storageLocation: 'Gudang Kering',
      storageCondition: 'DRY',
      isActive: true,
      sppgId: sppg.id,
      calories: 446,
      protein: 36,
      carbohydrates: 30,
      fat: 20,
      fiber: 9.3,
      // Vitamins
      vitaminB1: 0.87,
      vitaminB2: 0.87,
      vitaminB3: 1.6,
      vitaminB6: 0.38,
      vitaminE: 0.85,
      folate: 375,
      // Minerals
      calcium: 277,
      iron: 15.7,
      magnesium: 280,
      phosphorus: 704,
      potassium: 1797,
      sodium: 2,
      zinc: 4.9
    },

    // SAYURAN
    {
      itemName: 'Wortel',
      itemCode: 'WRT-001',
      category: 'SAYURAN',
      unit: 'kg',
      currentStock: 35,
      minStock: 15,
      maxStock: 100,
      costPerUnit: 8000,
      storageLocation: 'Chiller',
      storageCondition: 'COOL',
      isActive: true,
      sppgId: sppg.id,
      calories: 41,
      protein: 0.9,
      carbohydrates: 10,
      fat: 0.2,
      fiber: 2.8,
      // Vitamins (TKPI Data)
      vitaminA: 835,     // mcg RAE - SUPER TINGGI!
      vitaminB1: 0.07,
      vitaminB2: 0.06,
      vitaminB3: 0.98,
      vitaminB6: 0.14,
      vitaminC: 6,
      vitaminE: 0.66,
      vitaminK: 13,
      folate: 19,
      // Minerals
      calcium: 33,
      iron: 0.3,
      magnesium: 12,
      phosphorus: 35,
      potassium: 320,
      sodium: 69,
      zinc: 0.24
    },
    {
      itemName: 'Bayam',
      itemCode: 'BYM-001',
      category: 'SAYURAN',
      unit: 'kg',
      currentStock: 20,
      minStock: 10,
      maxStock: 60,
      costPerUnit: 6000,
      storageLocation: 'Chiller',
      storageCondition: 'COOL',
      isActive: true,
      sppgId: sppg.id,
      calories: 23,
      protein: 2.9,
      carbohydrates: 3.6,
      fat: 0.4,
      fiber: 2.2,
      // Vitamins (TKPI Data)
      vitaminA: 469,
      vitaminB1: 0.08,
      vitaminB2: 0.19,
      vitaminB3: 0.72,
      vitaminB6: 0.2,
      vitaminC: 28,
      vitaminE: 2,
      vitaminK: 483,     // SUPER TINGGI vitamin K!
      folate: 194,
      // Minerals
      calcium: 99,
      iron: 2.7,
      magnesium: 79,
      phosphorus: 49,
      potassium: 558,
      sodium: 79,
      zinc: 0.5
    },
    {
      itemName: 'Ikan Nila',
      itemCode: 'IKN-001',
      category: 'PROTEIN',
      unit: 'kg',
      currentStock: 25,
      minStock: 10,
      maxStock: 60,
      costPerUnit: 35000,
      storageLocation: 'Freezer',
      storageCondition: 'FROZEN',
      isActive: true,
      sppgId: sppg.id,
      calories: 96,
      protein: 20,
      carbohydrates: 0,
      fat: 1.7,
      fiber: 0
    },
    {
      itemName: 'Ikan Lele',
      itemCode: 'IKL-001',
      category: 'PROTEIN',
      unit: 'kg',
      currentStock: 20,
      minStock: 10,
      maxStock: 50,
      costPerUnit: 28000,
      storageLocation: 'Freezer',
      storageCondition: 'FROZEN',
      isActive: true,
      sppgId: sppg.id,
      calories: 105,
      protein: 17.7,
      carbohydrates: 0,
      fat: 3.5,
      fiber: 0
    },
    {
      itemName: 'Tempe',
      itemCode: 'TMP-001',
      category: 'PROTEIN',
      unit: 'kg',
      currentStock: 20,
      minStock: 10,
      maxStock: 50,
      costPerUnit: 12000,
      storageLocation: 'Chiller',
      storageCondition: 'COOL',
      isActive: true,
      sppgId: sppg.id,
      calories: 193,
      protein: 20.8,
      carbohydrates: 7.6,
      fat: 8.8,
      fiber: 1.4
    },
    {
      itemName: 'Tahu',
      itemCode: 'TAH-001',
      category: 'PROTEIN',
      unit: 'kg',
      currentStock: 18,
      minStock: 8,
      maxStock: 40,
      costPerUnit: 10000,
      storageLocation: 'Chiller',
      storageCondition: 'COOL',
      isActive: true,
      sppgId: sppg.id,
      calories: 76,
      protein: 8,
      carbohydrates: 1.9,
      fat: 4.8,
      fiber: 0.3
    },
    {
      itemName: 'Kedelai Kuning',
      itemCode: 'KDL-001',
      category: 'PROTEIN',
      unit: 'kg',
      currentStock: 25,
      minStock: 10,
      maxStock: 80,
      costPerUnit: 15000,
      storageLocation: 'Gudang Kering',
      storageCondition: 'DRY',
      isActive: true,
      sppgId: sppg.id,
      calories: 446,
      protein: 36,
      carbohydrates: 30,
      fat: 20,
      fiber: 9.3
    },

    // SAYURAN
    {
      itemName: 'Wortel',
      itemCode: 'WRT-001',
      category: 'SAYURAN',
      unit: 'kg',
      currentStock: 35,
      minStock: 15,
      maxStock: 100,
      costPerUnit: 8000,
      storageLocation: 'Chiller',
      storageCondition: 'COOL',
      isActive: true,
      sppgId: sppg.id,
      calories: 41,
      protein: 0.9,
      carbohydrates: 10,
      fat: 0.2,
      fiber: 2.8
    },
    {
      itemName: 'Bayam',
      itemCode: 'BYM-001',
      category: 'SAYURAN',
      unit: 'kg',
      currentStock: 20,
      minStock: 10,
      maxStock: 60,
      costPerUnit: 6000,
      storageLocation: 'Chiller',
      storageCondition: 'COOL',
      isActive: true,
      sppgId: sppg.id,
      calories: 23,
      protein: 2.9,
      carbohydrates: 3.6,
      fat: 0.4,
      fiber: 2.2
    },
    {
      itemName: 'Kangkung',
      itemCode: 'KNG-001',
      category: 'SAYURAN',
      unit: 'kg',
      currentStock: 15,
      minStock: 8,
      maxStock: 50,
      costPerUnit: 5000,
      storageLocation: 'Chiller',
      storageCondition: 'COOL',
      isActive: true,
      sppgId: sppg.id,
      calories: 19,
      protein: 2.6,
      carbohydrates: 3.1,
      fat: 0.2,
      fiber: 2
    },
    {
      itemName: 'Tomat',
      itemCode: 'TMT-001',
      category: 'SAYURAN',
      unit: 'kg',
      currentStock: 25,
      minStock: 10,
      maxStock: 70,
      costPerUnit: 9000,
      storageLocation: 'Chiller',
      storageCondition: 'COOL',
      isActive: true,
      sppgId: sppg.id,
      calories: 18,
      protein: 0.9,
      carbohydrates: 3.9,
      fat: 0.2,
      fiber: 1.2
    },
    {
      itemName: 'Sawi Hijau',
      itemCode: 'SWH-001',
      category: 'SAYURAN',
      unit: 'kg',
      currentStock: 18,
      minStock: 10,
      maxStock: 60,
      costPerUnit: 5500,
      storageLocation: 'Chiller',
      storageCondition: 'COOL',
      isActive: true,
      sppgId: sppg.id,
      calories: 13,
      protein: 1.5,
      carbohydrates: 2.2,
      fat: 0.2,
      fiber: 1,
      // Vitamins (TKPI Data)
      vitaminA: 969,
      vitaminB1: 0.05,
      vitaminB2: 0.1,
      vitaminB3: 0.5,
      vitaminB6: 0.09,
      vitaminC: 52,
      vitaminE: 0.8,
      vitaminK: 389,
      folate: 79,
      // Minerals
      calcium: 220,
      iron: 2.9,
      magnesium: 12,
      phosphorus: 38,
      potassium: 252,
      sodium: 18,
      zinc: 0.2
    },
    {
      itemName: 'Kentang',
      itemCode: 'KNT-001',
      category: 'SAYURAN',
      unit: 'kg',
      currentStock: 40,
      minStock: 20,
      maxStock: 120,
      costPerUnit: 12000,
      storageLocation: 'Gudang Kering',
      storageCondition: 'ROOM_TEMP',
      isActive: true,
      sppgId: sppg.id,
      calories: 77,
      protein: 2,
      carbohydrates: 17,
      fat: 0.1,
      fiber: 2.2,
      // Vitamins
      vitaminB1: 0.08,
      vitaminB2: 0.03,
      vitaminB3: 1.1,
      vitaminB6: 0.3,
      vitaminC: 20,
      folate: 15,
      // Minerals
      calcium: 12,
      iron: 0.8,
      magnesium: 23,
      phosphorus: 57,
      potassium: 421,
      sodium: 6,
      zinc: 0.3
    },
    {
      itemName: 'Buncis',
      itemCode: 'BNC-001',
      category: 'SAYURAN',
      unit: 'kg',
      currentStock: 18,
      minStock: 10,
      maxStock: 60,
      costPerUnit: 10000,
      storageLocation: 'Chiller',
      storageCondition: 'COOL',
      isActive: true,
      sppgId: sppg.id,
      calories: 31,
      protein: 1.8,
      carbohydrates: 7,
      fat: 0.2,
      fiber: 2.7,
      // Vitamins
      vitaminA: 35,
      vitaminB1: 0.08,
      vitaminB2: 0.1,
      vitaminB3: 0.7,
      vitaminB6: 0.14,
      vitaminC: 12,
      vitaminK: 43,
      folate: 33,
      // Minerals
      calcium: 37,
      iron: 1,
      magnesium: 25,
      phosphorus: 38,
      potassium: 211,
      sodium: 6,
      zinc: 0.2
    },
    {
      itemName: 'Labu Siam',
      itemCode: 'LBS-001',
      category: 'SAYURAN',
      unit: 'kg',
      currentStock: 25,
      minStock: 10,
      maxStock: 80,
      costPerUnit: 6000,
      storageLocation: 'Chiller',
      storageCondition: 'COOL',
      isActive: true,
      sppgId: sppg.id,
      calories: 19,
      protein: 0.8,
      carbohydrates: 4.5,
      fat: 0.1,
      fiber: 1.7,
      // Vitamins
      vitaminC: 7,
      vitaminB6: 0.08,
      folate: 18,
      // Minerals
      calcium: 17,
      iron: 0.3,
      magnesium: 12,
      phosphorus: 18,
      potassium: 125,
      sodium: 2,
      zinc: 0.7
    },
    {
      itemName: 'Kacang Panjang',
      itemCode: 'KCG-001',
      category: 'SAYURAN',
      unit: 'kg',
      currentStock: 20,
      minStock: 8,
      maxStock: 70,
      costPerUnit: 7000,
      storageLocation: 'Chiller',
      storageCondition: 'COOL',
      isActive: true,
      sppgId: sppg.id,
      calories: 47,
      protein: 2.8,
      carbohydrates: 8,
      fat: 0.4,
      fiber: 3.4,
      // Vitamins (TKPI Data - LENGKAP!)
      vitaminA: 865,      // mcg RAE - TINGGI vitamin A!
      vitaminB1: 0.09,    // mg (Thiamin)
      vitaminB2: 0.11,    // mg (Riboflavin)
      vitaminB3: 0.8,     // mg (Niacin)
      vitaminB6: 0.14,    // mg
      vitaminC: 18,       // mg - sumber vitamin C bagus
      vitaminE: 0.6,      // mg
      vitaminK: 43,       // mcg
      folate: 42,         // mcg
      // Minerals (TKPI Data)
      calcium: 50,        // mg
      iron: 0.7,          // mg
      magnesium: 28,      // mg
      phosphorus: 38,     // mg
      potassium: 230,     // mg
      sodium: 3,          // mg
      zinc: 0.3,          // mg
      selenium: 1         // mcg
    },

    // BUAH-BUAHAN
    {
      itemName: 'Pisang',
      itemCode: 'PSG-001',
      category: 'BUAH',
      unit: 'kg',
      currentStock: 30,
      minStock: 15,
      maxStock: 80,
      costPerUnit: 12000,
      storageLocation: 'Gudang Kering',
      storageCondition: 'ROOM_TEMP',
      isActive: true,
      sppgId: sppg.id,
      calories: 89,
      protein: 1.1,
      carbohydrates: 23,
      fat: 0.3,
      fiber: 2.6
    },
    {
      itemName: 'Jeruk',
      itemCode: 'JRK-001',
      category: 'BUAH',
      unit: 'kg',
      currentStock: 20,
      minStock: 10,
      maxStock: 60,
      costPerUnit: 18000,
      storageLocation: 'Chiller',
      storageCondition: 'COOL',
      isActive: true,
      sppgId: sppg.id,
      calories: 47,
      protein: 0.9,
      carbohydrates: 12,
      fat: 0.1,
      fiber: 2.4
    },
    {
      itemName: 'Apel',
      itemCode: 'APL-001',
      category: 'BUAH',
      unit: 'kg',
      currentStock: 25,
      minStock: 12,
      maxStock: 70,
      costPerUnit: 25000,
      storageLocation: 'Chiller',
      storageCondition: 'COOL',
      isActive: true,
      sppgId: sppg.id,
      calories: 52,
      protein: 0.3,
      carbohydrates: 14,
      fat: 0.2,
      fiber: 2.4
    },
    {
      itemName: 'Semangka',
      itemCode: 'SMK-001',
      category: 'BUAH',
      unit: 'kg',
      currentStock: 15,
      minStock: 8,
      maxStock: 50,
      costPerUnit: 8000,
      storageLocation: 'Chiller',
      storageCondition: 'COOL',
      isActive: true,
      sppgId: sppg.id,
      calories: 30,
      protein: 0.6,
      carbohydrates: 8,
      fat: 0.2,
      fiber: 0.4
    },

    // SUSU & OLAHAN
    {
      itemName: 'Susu UHT',
      itemCode: 'SSU-001',
      category: 'SUSU_OLAHAN',
      unit: 'liter',
      currentStock: 100,
      minStock: 40,
      maxStock: 300,
      costPerUnit: 18000,
      storageLocation: 'Gudang Kering',
      storageCondition: 'ROOM_TEMP',
      isActive: true,
      sppgId: sppg.id,
      calories: 61,
      protein: 3.2,
      carbohydrates: 4.8,
      fat: 3.3,
      fiber: 0
    },
    {
      itemName: 'Keju Cheddar',
      itemCode: 'KJC-001',
      category: 'SUSU_OLAHAN',
      unit: 'kg',
      currentStock: 10,
      minStock: 5,
      maxStock: 30,
      costPerUnit: 120000,
      storageLocation: 'Chiller',
      storageCondition: 'COOL',
      isActive: true,
      sppgId: sppg.id,
      calories: 403,
      protein: 25,
      carbohydrates: 1.3,
      fat: 33,
      fiber: 0
    },
    {
      itemName: 'Yogurt',
      itemCode: 'YGT-001',
      category: 'SUSU_OLAHAN',
      unit: 'kg',
      currentStock: 15,
      minStock: 8,
      maxStock: 50,
      costPerUnit: 45000,
      storageLocation: 'Chiller',
      storageCondition: 'COOL',
      isActive: true,
      sppgId: sppg.id,
      calories: 59,
      protein: 3.5,
      carbohydrates: 4.7,
      fat: 3.3,
      fiber: 0
    },
    {
      itemName: 'Keju Cheddar Parut',
      itemCode: 'KJU-001',
      category: 'SUSU_OLAHAN',
      unit: 'kg',
      currentStock: 10,
      minStock: 5,
      maxStock: 30,
      costPerUnit: 120000,
      storageLocation: 'Chiller',
      storageCondition: 'COOL',
      isActive: true,
      sppgId: sppg.id,
      calories: 403,
      protein: 25,
      carbohydrates: 1.3,
      fat: 33,
      fiber: 0
    },

    // BUMBU & REMPAH
    {
      itemName: 'Garam',
      itemCode: 'GRM-001',
      category: 'BUMBU_REMPAH',
      unit: 'kg',
      currentStock: 10,
      minStock: 5,
      maxStock: 30,
      costPerUnit: 5000,
      storageLocation: 'Gudang Kering',
      storageCondition: 'DRY',
      isActive: true,
      sppgId: sppg.id,
      calories: 0,
      protein: 0,
      carbohydrates: 0,
      fat: 0,
      fiber: 0
    },
    {
      itemName: 'Gula Pasir',
      itemCode: 'GLP-001',
      category: 'BUMBU_REMPAH',
      unit: 'kg',
      currentStock: 25,
      minStock: 10,
      maxStock: 80,
      costPerUnit: 14000,
      storageLocation: 'Gudang Kering',
      storageCondition: 'DRY',
      isActive: true,
      sppgId: sppg.id,
      calories: 387,
      protein: 0,
      carbohydrates: 100,
      fat: 0,
      fiber: 0
    },
    {
      itemName: 'Bawang Merah',
      itemCode: 'BWM-001',
      category: 'BUMBU_REMPAH',
      unit: 'kg',
      currentStock: 15,
      minStock: 8,
      maxStock: 50,
      costPerUnit: 35000,
      storageLocation: 'Gudang Kering',
      storageCondition: 'ROOM_TEMP',
      isActive: true,
      sppgId: sppg.id,
      calories: 40,
      protein: 1.1,
      carbohydrates: 9.3,
      fat: 0.1,
      fiber: 1.7
    },
    {
      itemName: 'Bawang Putih',
      itemCode: 'BWP-001',
      category: 'BUMBU_REMPAH',
      unit: 'kg',
      currentStock: 12,
      minStock: 6,
      maxStock: 40,
      costPerUnit: 38000,
      storageLocation: 'Gudang Kering',
      storageCondition: 'ROOM_TEMP',
      isActive: true,
      sppgId: sppg.id,
      calories: 149,
      protein: 6.4,
      carbohydrates: 33,
      fat: 0.5,
      fiber: 2.1
    },
    {
      itemName: 'Kecap Manis',
      itemCode: 'KCM-001',
      category: 'BUMBU_REMPAH',
      unit: 'liter',
      currentStock: 20,
      minStock: 10,
      maxStock: 60,
      costPerUnit: 22000,
      storageLocation: 'Gudang Kering',
      storageCondition: 'ROOM_TEMP',
      isActive: true,
      sppgId: sppg.id,
      calories: 224,
      protein: 5.8,
      carbohydrates: 48,
      fat: 0.1,
      fiber: 0.8
    },
    {
      itemName: 'Saos Tomat',
      itemCode: 'STM-001',
      category: 'BUMBU_REMPAH',
      unit: 'liter',
      currentStock: 15,
      minStock: 8,
      maxStock: 50,
      costPerUnit: 25000,
      storageLocation: 'Gudang Kering',
      storageCondition: 'ROOM_TEMP',
      isActive: true,
      sppgId: sppg.id,
      calories: 101,
      protein: 1.8,
      carbohydrates: 24,
      fat: 0.3,
      fiber: 1.5
    },

    // MINYAK & LEMAK
    {
      itemName: 'Minyak Goreng',
      itemCode: 'MYK-001',
      category: 'MINYAK_LEMAK',
      unit: 'liter',
      currentStock: 40,
      minStock: 20,
      maxStock: 120,
      costPerUnit: 16000,
      storageLocation: 'Gudang Kering',
      storageCondition: 'ROOM_TEMP',
      isActive: true,
      sppgId: sppg.id,
      calories: 884,
      protein: 0,
      carbohydrates: 0,
      fat: 100,
      fiber: 0
    },
    {
      itemName: 'Mentega',
      itemCode: 'MTG-001',
      category: 'MINYAK_LEMAK',
      unit: 'kg',
      currentStock: 10,
      minStock: 5,
      maxStock: 30,
      costPerUnit: 85000,
      storageLocation: 'Chiller',
      storageCondition: 'COOL',
      isActive: true,
      sppgId: sppg.id,
      calories: 717,
      protein: 0.9,
      carbohydrates: 0.1,
      fat: 81,
      fiber: 0
    },
    {
      itemName: 'Margarin',
      itemCode: 'MRG-001',
      category: 'MINYAK_LEMAK',
      unit: 'kg',
      currentStock: 12,
      minStock: 6,
      maxStock: 35,
      costPerUnit: 45000,
      storageLocation: 'Chiller',
      storageCondition: 'COOL',
      isActive: true,
      sppgId: sppg.id,
      calories: 720,
      protein: 0.2,
      carbohydrates: 0.9,
      fat: 81,
      fiber: 0
    },
    {
      itemName: 'Santan Kelapa',
      itemCode: 'SNT-001',
      category: 'MINYAK_LEMAK',
      unit: 'liter',
      currentStock: 20,
      minStock: 10,
      maxStock: 60,
      costPerUnit: 12000,
      storageLocation: 'Chiller',
      storageCondition: 'COOL',
      isActive: true,
      sppgId: sppg.id,
      calories: 230,
      protein: 2.3,
      carbohydrates: 6,
      fat: 24,
      fiber: 2.2
    },
    {
      itemName: 'Kelapa Parut',
      itemCode: 'KLP-001',
      category: 'MINYAK_LEMAK',
      unit: 'kg',
      currentStock: 15,
      minStock: 8,
      maxStock: 40,
      costPerUnit: 15000,
      storageLocation: 'Chiller',
      storageCondition: 'COOL',
      isActive: true,
      sppgId: sppg.id,
      calories: 354,
      protein: 3.3,
      carbohydrates: 15,
      fat: 33,
      fiber: 9
    },

    // SAYURAN TAMBAHAN (for Sundanese dishes)
    {
      itemName: 'Nangka Muda',
      itemCode: 'NKM-001',
      category: 'SAYURAN',
      unit: 'kg',
      currentStock: 20,
      minStock: 10,
      maxStock: 60,
      costPerUnit: 15000,
      storageLocation: 'Gudang Kering',
      storageCondition: 'ROOM_TEMP',
      isActive: true,
      sppgId: sppg.id,
      calories: 95,
      protein: 1.7,
      carbohydrates: 23,
      fat: 0.6,
      fiber: 1.5
    },
    {
      itemName: 'Kol',
      itemCode: 'KOL-001',
      category: 'SAYURAN',
      unit: 'kg',
      currentStock: 25,
      minStock: 12,
      maxStock: 70,
      costPerUnit: 8000,
      storageLocation: 'Chiller',
      storageCondition: 'COOL',
      isActive: true,
      sppgId: sppg.id,
      calories: 25,
      protein: 1.3,
      carbohydrates: 6,
      fat: 0.1,
      fiber: 2.5
    },
    {
      itemName: 'Jagung Manis',
      itemCode: 'JGM-001',
      category: 'SAYURAN',
      unit: 'kg',
      currentStock: 20,
      minStock: 10,
      maxStock: 60,
      costPerUnit: 10000,
      storageLocation: 'Chiller',
      storageCondition: 'COOL',
      isActive: true,
      sppgId: sppg.id,
      calories: 86,
      protein: 3.3,
      carbohydrates: 19,
      fat: 1.4,
      fiber: 2
    },
    {
      itemName: 'Timun',
      itemCode: 'TMN-001',
      category: 'SAYURAN',
      unit: 'kg',
      currentStock: 15,
      minStock: 8,
      maxStock: 50,
      costPerUnit: 8000,
      storageLocation: 'Chiller',
      storageCondition: 'COOL',
      isActive: true,
      sppgId: sppg.id,
      calories: 15,
      protein: 0.7,
      carbohydrates: 3.6,
      fat: 0.1,
      fiber: 0.5
    },

    // BUMBU & REMPAH TAMBAHAN (Traditional spices)
    {
      itemName: 'Gula Merah',
      itemCode: 'GLM-001',
      category: 'BUMBU_REMPAH',
      unit: 'kg',
      currentStock: 15,
      minStock: 8,
      maxStock: 50,
      costPerUnit: 25000,
      storageLocation: 'Gudang Kering',
      storageCondition: 'DRY',
      isActive: true,
      sppgId: sppg.id,
      calories: 380,
      protein: 0.3,
      carbohydrates: 98,
      fat: 0.1,
      fiber: 0
    },
    {
      itemName: 'Lengkuas',
      itemCode: 'LKS-001',
      category: 'BUMBU_REMPAH',
      unit: 'kg',
      currentStock: 10,
      minStock: 5,
      maxStock: 30,
      costPerUnit: 20000,
      storageLocation: 'Gudang Kering',
      storageCondition: 'ROOM_TEMP',
      isActive: true,
      sppgId: sppg.id,
      calories: 71,
      protein: 1,
      carbohydrates: 15,
      fat: 1,
      fiber: 2
    },
    {
      itemName: 'Kemiri',
      itemCode: 'KMR-001',
      category: 'BUMBU_REMPAH',
      unit: 'kg',
      currentStock: 5,
      minStock: 3,
      maxStock: 15,
      costPerUnit: 80000,
      storageLocation: 'Gudang Kering',
      storageCondition: 'DRY',
      isActive: true,
      sppgId: sppg.id,
      calories: 718,
      protein: 8,
      carbohydrates: 8,
      fat: 73,
      fiber: 6
    },
    {
      itemName: 'Kunyit',
      itemCode: 'KNY-001',
      category: 'BUMBU_REMPAH',
      unit: 'kg',
      currentStock: 8,
      minStock: 4,
      maxStock: 25,
      costPerUnit: 18000,
      storageLocation: 'Gudang Kering',
      storageCondition: 'ROOM_TEMP',
      isActive: true,
      sppgId: sppg.id,
      calories: 312,
      protein: 9.7,
      carbohydrates: 67,
      fat: 3.2,
      fiber: 22.7
    },
    {
      itemName: 'Jahe',
      itemCode: 'JAH-001',
      category: 'BUMBU_REMPAH',
      unit: 'kg',
      currentStock: 10,
      minStock: 5,
      maxStock: 30,
      costPerUnit: 22000,
      storageLocation: 'Gudang Kering',
      storageCondition: 'ROOM_TEMP',
      isActive: true,
      sppgId: sppg.id,
      calories: 80,
      protein: 1.8,
      carbohydrates: 18,
      fat: 0.8,
      fiber: 2
    },
    {
      itemName: 'Sereh',
      itemCode: 'SRH-001',
      category: 'BUMBU_REMPAH',
      unit: 'kg',
      currentStock: 8,
      minStock: 4,
      maxStock: 25,
      costPerUnit: 15000,
      storageLocation: 'Gudang Kering',
      storageCondition: 'ROOM_TEMP',
      isActive: true,
      sppgId: sppg.id,
      calories: 99,
      protein: 1.8,
      carbohydrates: 25,
      fat: 0.5,
      fiber: 0
    },
    {
      itemName: 'Daun Salam',
      itemCode: 'DSL-001',
      category: 'BUMBU_REMPAH',
      unit: 'kg',
      currentStock: 3,
      minStock: 2,
      maxStock: 10,
      costPerUnit: 30000,
      storageLocation: 'Gudang Kering',
      storageCondition: 'DRY',
      isActive: true,
      sppgId: sppg.id,
      calories: 313,
      protein: 7.6,
      carbohydrates: 75,
      fat: 8.4,
      fiber: 26
    },
    {
      itemName: 'Daun Jeruk',
      itemCode: 'DJK-001',
      category: 'BUMBU_REMPAH',
      unit: 'kg',
      currentStock: 3,
      minStock: 2,
      maxStock: 10,
      costPerUnit: 40000,
      storageLocation: 'Gudang Kering',
      storageCondition: 'DRY',
      isActive: true,
      sppgId: sppg.id,
      calories: 47,
      protein: 0.7,
      carbohydrates: 11,
      fat: 0.2,
      fiber: 10.6
    },
    {
      itemName: 'Cabe Rawit',
      itemCode: 'CBR-001',
      category: 'BUMBU_REMPAH',
      unit: 'kg',
      currentStock: 8,
      minStock: 4,
      maxStock: 25,
      costPerUnit: 45000,
      storageLocation: 'Chiller',
      storageCondition: 'COOL',
      isActive: true,
      sppgId: sppg.id,
      calories: 40,
      protein: 1.9,
      carbohydrates: 9,
      fat: 0.4,
      fiber: 1.5
    },
    {
      itemName: 'Ketumbar',
      itemCode: 'KTB-001',
      category: 'BUMBU_REMPAH',
      unit: 'kg',
      currentStock: 5,
      minStock: 3,
      maxStock: 15,
      costPerUnit: 35000,
      storageLocation: 'Gudang Kering',
      storageCondition: 'DRY',
      isActive: true,
      sppgId: sppg.id,
      calories: 298,
      protein: 12,
      carbohydrates: 55,
      fat: 18,
      fiber: 42
    },
    {
      itemName: 'Asam Jawa',
      itemCode: 'ASM-001',
      category: 'BUMBU_REMPAH',
      unit: 'kg',
      currentStock: 10,
      minStock: 5,
      maxStock: 30,
      costPerUnit: 8000,
      storageLocation: 'Gudang Kering',
      storageCondition: 'DRY',
      isActive: true,
      sppgId: sppg.id,
      calories: 239,
      protein: 2.8,
      carbohydrates: 62,
      fat: 0.6,
      fiber: 5.1
    },
    {
      itemName: 'Daun Pandan',
      itemCode: 'PDN-001',
      category: 'BUMBU_REMPAH',
      unit: 'kg',
      currentStock: 3,
      minStock: 2,
      maxStock: 12,
      costPerUnit: 100000,
      storageLocation: 'Chiller',
      storageCondition: 'COOL',
      isActive: true,
      sppgId: sppg.id,
      calories: 30,
      protein: 0,
      carbohydrates: 0,
      fat: 0,
      fiber: 0
    },

    // PROTEIN (Protein Nabati)
    {
      itemName: 'Kacang Tanah',
      itemCode: 'KCT-001',
      category: 'PROTEIN',
      unit: 'kg',
      currentStock: 20,
      minStock: 10,
      maxStock: 60,
      costPerUnit: 18000,
      storageLocation: 'Gudang Kering',
      storageCondition: 'DRY',
      isActive: true,
      sppgId: sppg.id,
      calories: 567,
      protein: 25.8,
      carbohydrates: 16,
      fat: 49,
      fiber: 8.5
    },

    // KARBOHIDRAT TAMBAHAN
    {
      itemName: 'Ubi Ungu',
      itemCode: 'UBU-001',
      category: 'KARBOHIDRAT',
      unit: 'kg',
      currentStock: 25,
      minStock: 12,
      maxStock: 70,
      costPerUnit: 12000,
      storageLocation: 'Gudang Kering',
      storageCondition: 'ROOM_TEMP',
      isActive: true,
      sppgId: sppg.id,
      calories: 90,
      protein: 1.6,
      carbohydrates: 21,
      fat: 0.1,
      fiber: 3
    },

    // LAINNYA (Miscellaneous)
    {
      itemName: 'Kerupuk Udang',
      itemCode: 'KRK-001',
      category: 'LAINNYA',
      unit: 'kg',
      currentStock: 15,
      minStock: 8,
      maxStock: 50,
      costPerUnit: 80000,
      storageLocation: 'Gudang Kering',
      storageCondition: 'DRY',
      isActive: true,
      sppgId: sppg.id,
      calories: 500,
      protein: 8,
      carbohydrates: 60,
      fat: 25,
      fiber: 2
    },
    {
      itemName: 'Selai Cokelat',
      itemCode: 'SLC-001',
      category: 'LAINNYA',
      unit: 'kg',
      currentStock: 10,
      minStock: 5,
      maxStock: 30,
      costPerUnit: 65000,
      storageLocation: 'Gudang Kering',
      storageCondition: 'ROOM_TEMP',
      isActive: true,
      sppgId: sppg.id,
      calories: 539,
      protein: 5.4,
      carbohydrates: 62,
      fat: 30,
      fiber: 5
    },
    {
      itemName: 'Bubuk Cokelat',
      itemCode: 'CKT-001',
      category: 'LAINNYA',
      unit: 'kg',
      currentStock: 8,
      minStock: 4,
      maxStock: 25,
      costPerUnit: 95000,
      storageLocation: 'Gudang Kering',
      storageCondition: 'DRY',
      isActive: true,
      sppgId: sppg.id,
      calories: 228,
      protein: 20,
      carbohydrates: 58,
      fat: 14,
      fiber: 33
    },

    // KEMASAN (Packaging materials)
    {
      itemName: 'Daun Pisang',
      itemCode: 'DPS-001',
      category: 'LAINNYA',
      unit: 'lembar',
      currentStock: 100,
      minStock: 50,
      maxStock: 300,
      costPerUnit: 500,
      storageLocation: 'Gudang Kering',
      storageCondition: 'ROOM_TEMP',
      isActive: true,
      sppgId: sppg.id,
      calories: 0,
      protein: 0,
      carbohydrates: 0,
      fat: 0,
      fiber: 0
    },
  ]

  // Clear existing inventory items for this SPPG first
  await prisma.inventoryItem.deleteMany({
    where: { sppgId: sppg.id }
  })

  // Use createMany for bulk insert
  const result = await prisma.inventoryItem.createMany({
    data: inventoryItems,
    skipDuplicates: true
  })

  console.log(`  ✓ Created ${result.count} inventory items for SPPG: ${sppg.name}`)
  
  return result
}

// Run directly if executed as script
if (require.main === module) {
  seedInventory()
    .then(() => {
      console.log('✅ Inventory seed completed!')
      process.exit(0)
    })
    .catch((error) => {
      console.error('❌ Inventory seed failed:', error)
      process.exit(1)
    })
    .finally(async () => {
      await prisma.$disconnect()
    })
}
