#!/bin/bash

echo "🔍 Production Access Debug Checker"
echo "=================================="
echo ""

# Check if server is running
if pgrep -f "next dev" > /dev/null; then
    echo "✅ Development server is running"
else
    echo "❌ Development server is NOT running"
    echo "   Run: npm run dev"
    exit 1
fi

echo ""
echo "📋 Quick Checklist:"
echo ""
echo "1️⃣  Server restarted after middleware changes?"
echo "   - Stop server: Ctrl+C"
echo "   - Start server: npm run dev"
echo ""
echo "2️⃣  Browser cache cleared?"
echo "   - Mac: Cmd+Shift+R"
echo "   - Windows: Ctrl+Shift+R"
echo ""
echo "3️⃣  Logged in with correct account?"
echo "   - Email: admin@sppg-purwakarta.com"
echo "   - Password: password123"
echo ""
echo "4️⃣  When you click Production link, check terminal for:"
echo "   - Look for lines starting with [Middleware]"
echo "   - Should see 🚀 REQUEST START"
echo "   - Should see 🏭 PRODUCTION ACCESS CHECK"
echo ""
echo "=================================="
echo ""
echo "🎯 WHAT TO COPY FROM TERMINAL:"
echo ""
echo "Copy ALL lines between the === separators:"
echo ""
echo "================================================================================"
echo "[Middleware] 🚀 REQUEST START: ..."
echo "[Middleware] 📋 Route Classification: ..."
echo "[Middleware] 🔐 Session Check: ..."
echo "[Middleware] 🏢 SPPG Route Check: ..."
echo "[Middleware] 👤 SPPG User Validation: ..."
echo "[Middleware] 🏭 PRODUCTION ACCESS CHECK: ..."
echo "[Middleware] ✅✅✅ Production access GRANTED"
echo "  OR"
echo "[Middleware] ❌❌❌ FAILED: Production access DENIED"
echo "================================================================================"
echo ""
echo "Then paste those logs in your next message!"
echo ""
