#!/bin/bash

# Production Access Debug Script
# Helps diagnose why sidebar production link redirects to dashboard

echo "🔍 Production Access Debug Helper"
echo "=================================="
echo ""

echo "📋 Step-by-Step Debugging Guide:"
echo ""

echo "1️⃣  Clear Browser Cache & Cookies"
echo "   - Open browser DevTools (F12)"
echo "   - Right-click on Refresh button → Empty Cache and Hard Reload"
echo "   - Or go to Application tab → Clear all storage"
echo "   - Reason: Old auth session might be cached"
echo ""

echo "2️⃣  Check Current Login Session"
echo "   - Open browser console (F12)"
echo "   - Run this command:"
echo "   > fetch('/api/auth/session').then(r => r.json()).then(console.log)"
echo ""
echo "   Expected output:"
echo "   {"
echo "     user: {"
echo "       email: 'your-email@sppg-purwakarta.com',"
echo "       userRole: 'SPPG_PRODUKSI_MANAGER', // or one of 6 allowed roles"
echo "       sppgId: 'clxxx...' // Should NOT be null"
echo "     }"
echo "   }"
echo ""

echo "3️⃣  Check canAccess Function in Browser"
echo "   - Open browser console"
echo "   - Check if sidebar is hiding the link:"
echo "   - Inspect Production link in sidebar"
echo "   - If link is missing/hidden → canAccess returned false"
echo ""

echo "4️⃣  Verify Login Credentials"
echo "   - Logout completely from app"
echo "   - Login with one of these accounts:"
echo ""
echo "   ✅ RECOMMENDED:"
echo "   Email: produksi@sppg-purwakarta.com"
echo "   Password: password123"
echo "   Role: SPPG_PRODUKSI_MANAGER"
echo ""
echo "   ✅ ALTERNATIVE:"
echo "   Email: admin@sppg-purwakarta.com"
echo "   Password: password123"
echo "   Role: SPPG_ADMIN"
echo ""

echo "5️⃣  Check Middleware Logs (Server Side)"
echo "   - Check terminal running 'npm run dev'"
echo "   - Look for any redirect logs when accessing /production"
echo "   - Middleware should NOT redirect if role is correct"
echo ""

echo "6️⃣  Direct URL Test"
echo "   - Try navigating directly to: http://localhost:3000/production"
echo "   - If this works but sidebar doesn't → client-side issue"
echo "   - If this also redirects → server-side middleware issue"
echo ""

echo "7️⃣  Database Verification"
echo "   - Open Prisma Studio: npx prisma studio"
echo "   - Go to User table"
echo "   - Find your user by email"
echo "   - Verify:"
echo "     ✅ userRole is one of: SPPG_KEPALA, SPPG_ADMIN, SPPG_PRODUKSI_MANAGER,"
echo "        SPPG_STAFF_DAPUR, SPPG_STAFF_QC, SPPG_AHLI_GIZI"
echo "     ✅ sppgId is NOT NULL"
echo "     ✅ isActive is true"
echo ""

echo "🐛 Common Issues & Solutions:"
echo ""
echo "Issue 1: Link not visible in sidebar"
echo "  Cause: canAccess('production') returning false"
echo "  Solution: Check user role matches one of 6 allowed roles"
echo ""
echo "Issue 2: Link visible but redirects"
echo "  Cause: Middleware blocking access"
echo "  Solution: Check middleware.ts allows your role"
echo ""
echo "Issue 3: Session shows wrong role"
echo "  Cause: Old cached session"
echo "  Solution: Logout → Clear cache → Login again"
echo ""
echo "Issue 4: sppgId is null"
echo "  Cause: User not associated with SPPG"
echo "  Solution: Check database, assign user to SPPG"
echo ""

echo "📁 Files to Check:"
echo ""
echo "1. src/hooks/use-auth.ts (line 212)"
echo "   case 'production':"
echo "     return hasRole(['SPPG_KEPALA', 'SPPG_ADMIN', 'SPPG_PRODUKSI_MANAGER',"
echo "                     'SPPG_STAFF_DAPUR', 'SPPG_STAFF_QC', 'SPPG_AHLI_GIZI'])"
echo ""
echo "2. src/middleware.ts (line 147-150)"
echo "   if (pathname.startsWith('/production') &&"
echo "       !['SPPG_KEPALA', 'SPPG_ADMIN', 'SPPG_PRODUKSI_MANAGER',"
echo "         'SPPG_STAFF_DAPUR', 'SPPG_STAFF_QC', 'SPPG_AHLI_GIZI'].includes(userRole))"
echo ""

echo "🧪 Quick Test Command:"
echo ""
echo "# Check if server is running and restart if needed"
echo "pkill -f 'next dev' && npm run dev"
echo ""

echo "💡 Still Having Issues?"
echo ""
echo "Try this complete reset:"
echo "1. Stop dev server (Ctrl+C)"
echo "2. rm -rf .next"
echo "3. npm run dev"
echo "4. Clear browser cache completely"
echo "5. Login with fresh credentials"
echo "6. Navigate to /production"
echo ""

echo "✅ If all else fails, provide these details:"
echo "   - Current user email"
echo "   - User role from database"
echo "   - Session output from browser console"
echo "   - Terminal logs when accessing /production"
echo "   - Screenshot of sidebar (is production link visible?)"
echo ""
